// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQI7aGOvvA_aTMA_q0f_uORiruKSLo2T4',
    appId: '1:934899196471:ios:635e0e047708dac24155b2',
    messagingSenderId: '934899196471',
    projectId: 'fir-auth-app-94d78',
    storageBucket: 'fir-auth-app-94d78.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQI7aGOvvA_aTMA_q0f_uORiruKSLo2T4',
    appId: '1:934899196471:ios:635e0e047708dac24155b2',
    messagingSenderId: '934899196471',
    projectId: 'fir-auth-app-94d78',
    storageBucket: 'fir-auth-app-94d78.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNTCs2i4Yol_7SWnUBhEBOsuq51vaoiwQ',
    appId: '1:934899196471:web:7e4dc420afc22d744155b2',
    messagingSenderId: '934899196471',
    projectId: 'fir-auth-app-94d78',
    authDomain: 'fir-auth-app-94d78.firebaseapp.com',
    storageBucket: 'fir-auth-app-94d78.firebasestorage.app',
    measurementId: 'G-QTDGTZBQ6P',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNTCs2i4Yol_7SWnUBhEBOsuq51vaoiwQ',
    appId: '1:934899196471:web:7e4dc420afc22d744155b2',
    messagingSenderId: '934899196471',
    projectId: 'fir-auth-app-94d78',
    authDomain: 'fir-auth-app-94d78.firebaseapp.com',
    storageBucket: 'fir-auth-app-94d78.firebasestorage.app',
    measurementId: 'G-QTDGTZBQ6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiQB2wtm-Co646tUfpXaJGxyWyBmNDPYY',
    appId: '1:934899196471:android:e772593b3ff932ff4155b2',
    messagingSenderId: '934899196471',
    projectId: 'fir-auth-app-94d78',
    storageBucket: 'fir-auth-app-94d78.firebasestorage.app',
  );
}
